# Generated by Django 4.2.4 on 2023-08-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated date and time')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Unique name for the user')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('first_name', models.CharField(max_length=128, verbose_name='First name')),
                ('middle_name', models.CharField(max_length=128, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last name')),
                ('nickname', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nickname')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/accounts/%Y/%m/', verbose_name='Profile picture')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='Male or Female')),
                ('type', models.CharField(choices=[('s', 'Student'), ('t', 'Teacher'), ('a', 'Administrator')], max_length=1, verbose_name='Student, Teacher or Administrator')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'indexes': [models.Index(fields=['phone_number'], name='accounts_us_phone_n_613c4a_idx'), models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'), models.Index(fields=['first_name', 'last_name', 'middle_name'], name='accounts_us_first_n_df104b_idx')],
            },
        ),
    ]
