# Generated by Django 4.2.4 on 2023-08-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_birthdate_user_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_date',
            new_name='birthdate',
        ),
    ]
