# Generated by Django 4.2.7 on 2023-12-01 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('number_of_questions', models.PositiveIntegerField(verbose_name='Savollar miqdori')),
                ('time_limit', models.PositiveIntegerField(verbose_name='Vaqti (minut)')),
                ('result', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar soni")),
                ('is_completed', models.BooleanField(default=False, verbose_name='Yakunlanganmi?')),
            ],
            options={
                'verbose_name': 'Urinish',
                'verbose_name_plural': 'Urinishlar',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Fan nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faollik statusi')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(verbose_name="Kategoriya ta'rifi")),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Mavzu nomi')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='tests.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['title'], name='tests_subje_title_b1d053_idx'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi"),
        ),
        migrations.AddField(
            model_name='attempt',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='tests.subject', verbose_name='Fan'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='tests.topic', verbose_name='Mavzu'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'title')},
        ),
    ]
