# Generated by Django 4.2.7 on 2023-12-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Savol turi')),
                ('prompt', models.CharField(max_length=256, verbose_name='Savol bayoni')),
                ('subjects', models.ManyToManyField(blank=True, related_name='question_types', to='tests.subject', verbose_name='Tegishli fanlar')),
            ],
            options={
                'verbose_name': 'Savol turi',
                'verbose_name_plural': 'Savol turlari',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('question', models.TextField(verbose_name='Savol')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/tests/questions/%Y/%m/', verbose_name='Picture')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='tests.subject', verbose_name='Fan')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='tests.topic', verbose_name='Mavzu')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='tests.questiontype', verbose_name='Savol turi')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Variant')),
                ('choice', models.CharField(max_length=128, verbose_name='Javob')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javobmi?")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='tests.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'unique_together': {('question', 'letter')},
            },
        ),
    ]
