# Generated by Django 4.2.7 on 2023-12-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('title', models.CharField(max_length=128, verbose_name='Asosiy sarlavha')),
                ('subtitle', models.CharField(max_length=256, verbose_name='Kichik sarlavha')),
                ('picture', models.ImageField(upload_to='images/banners/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivmi?')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
            },
        ),
    ]
